config/routes.rb
Rails.application.routes.draw do
  resources :foods

  resources :devices
  resources :events

  resources :buddies

  resources :reminders

  resources :registers
  
  resources :feeds

  devise_for :users
  devise_for :registers
  devise_scope :user do
  authenticated :user do
    root :to => 'feeds#index'
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root

      end
end
 
 get "devices/registers2"
 get "devices/index"
 match "devices/register2" => "devices#register2", :via => :post

end

app/models/register.rb
class Register < ActiveRecord::Base
  	
belongs_to :User
has_many :buddies
has_one :device
has_many :events
has_many :foods

  	has_attached_file :image, styles: { large: "300x300>", thumb: "100x100>"}
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	validates :name, :species , :breed, :gender , presence: true

 def save_pet
  render new_buddy_path
end

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController

	def show
    @register = Register.find(params[:id])
        @buddies = []
    current_user.registers.each do |pet|
      buds = Buddy.where(:register_id => pet.id)
      buds.each do |buddy|
        if buddy.register == pet
          @buddies += [buddy]
      end
    end
  end
    

  end
  def index
    @reg= Register.new
    @register = current_user.registers
    #Here im creating an array of pets to be showed to the current user who is considered to be a buddy that have access on these pets.

    @registers = []
    @buddies = Buddy.where(:user => current_user)
    @buddies.each do |buddy|
    if !@register.include?(buddy.register)
      @registers += [buddy.register]  
    end
    end   
  end
  

  def edit
  @register = Register.find(params[:id])
	end
	def update
  @register = Register.find(params[:id])
 	end
  
  
	def new
    @reg= Register.new
  	end
  def create
  @register = Register.new(register_params)
  @register.User = current_user
 
  if @register.save
  redirect_to registers_path
else
  render'new'
end
end


def destroy
  @register = Register.find(params[:id])
  @register.destroy
 
  redirect_to registers_path
end




def register1
pet_id = Rails.cache.read(:pet_id)

@register = Register.where(params[:pet_id]).first
@device = Device.where(:id => params[:text2].to_i).first
if (@device.User==current_user)
@device.Register =  @register
end
  if !(@device.User.blank?) then 
    respond_to do |format|
      if @device.save then 
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end
end 



 
private
  def register_params
    params.require(:register).permit(:name, :breed, :gender, :species, :image, :date_of_birth)
  end
end

app/views/registers/edit.html.erb
<div class="menu">
      
      <!-- Menu icon -->
      <div class="icon-close">
        <img src='close.png'>
      </div>

<!-- Menu -->
      <ul >
     

<li><%= link_to 'Back', registers_path %></li>
      </ul>
    </div>
     <!-- Main body -->
    <div class="jumbotron">

      <div class="icon-menu">
        <i class="fa fa-bars"></i>
        Menu
      </div>
   
<%= form_for :register, url: registers_path,:html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
   <%= f.label :image %><br>
  <%= f.file_field :image %>
</p>



  <p>
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </p>

 <p>  <%= f.label :Species %><br>
      <%= f.text_field :species %>


</p>

<p>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %>
</p>

<p>

<%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, :start_year => 1900, :end_year => Date.current.year %>
</p>






 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/registers/index.html.erb
<head>
  <link href='../app/assets/stylesheets/pets_index.css' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="../app/assets/javascripts/pets_index.js"></script>
</head>
<body >
  <div class="new-pet-form">
  <!--This part is the new pet form with its 
  button on the side of the page-->
    <div id="new-pet-button"><a href="#"><strong>New Pet!</strong></a></div>
    <%= form_for (@reg), url: registers_path,:html => { :multipart => true } do |f| %>
    <% if @reg.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reg.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @reg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    </p>
    <p>
      <%= f.label :breed %><br>
      <%= f.text_field :breed %>
    </p>
    <p>  <%= f.label :Species %><br>
      <%= f.text_field :species %>
    </p>
    <p>
      <%= f.label :gender %><br>
      <%= f.text_field :gender %>
    </p>
    <p>
      <%= f.label :date_of_birth %><br />
      <%= f.date_select :date_of_birth, :start_year => 1900, :end_year => Date.current.year %>
    </p>
    <p>
      <%= f.submit %>
    </p>
    <% end %>
    <!--end of side menu div-->
  </div>
  <div >
  <h1>My Pets</h1>
    <div class="pet-list" >
    <!--List of user's pets-->
    
      <% if current_user.registers.size==0 %>
      <em>There are not any pets currently in the system.</em> <br>
      <% else %>
      <ul>
        <% @register.each do |register| %>
        <%= link_to(register) do %>
        <li>
         <!--a pet-->
          <div class="pet">
            <div id="DEF">
              <%= register.species %>
              <%= register.breed %>
              <p><%= Date.current.year - register.date_of_birth.year %> years old</p>
            </div>
            <%= image_tag register.image.url(:thumb), class: '.pet-profile-photo-left' %>
            <div class="pet-info-right">
              <h3><%= register.name %></h3>
            </div>
          </div>
        </li>
        <% end %>
        <% end %>
      </ul>
      <% end %>
    </div>
    <!-- here im listing the pets that the current user have access to them as he is the buddy on these pets -->
    <% if !(@registers.empty?) then %>
    <div class="pet-list"></div>
   
    <!--List of user's pets they are buddies to-->
    <h2>Buddy's Pets</h2>
    <ul>
      <% @registers.each do |register| %>
      <%= link_to(register) do %>
      <li>
        <div class="pet">
          <div id="DEF">
            <%= register.species %>
            <%= register.breed %>
            <%= Date.current.year - register.date_of_birth.year %>
          </div>
          <%= image_tag register.image.url(:thumb), class: '.pet-profile-photo-left'%>
          <h3>
            <div class="pet-info-right"><%= register.name %></div>
          </h3>
          <%= link_to 'Edit', edit_register_path(register) %>
          <%= link_to 'Delete', buddy_path(register),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
        </div>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
  <% end %>
  </div>
  </div>
  </div>
</body>

app/views/registers/new.html.erb
<div class="menu">
      
      <!-- Menu icon -->
      <div class="icon-close">
        <img src='close.png'>
      </div>

<!-- Menu -->
      <ul >
     

<li><%= link_to 'Back', registers_path %></li>
      </ul>
    </div>
     <!-- Main body -->
    <div class="jumbotron">

      <div class="icon-menu">
        <i class="fa fa-bars"></i>
        Menu
      </div>
   
<%= form_for :register, url: registers_path,:html => { :multipart => true } do |f| %>
<% if @register.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@register.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @register.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
   <%= f.label :image %><br>
  <%= f.file_field :image %>
</p>



  <p>
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </p>

 <p>  <%= f.label :Species %><br>
      <%= f.text_field :species %>


</p>

<p>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %>
</p>

<p>

<%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, :start_year => 1900, :end_year => Date.current.year %>
</p>





 
  <p>
    <%= f.submit %>
  </p>
<% end %>

</div>

app/views/registers/show.html.erb
      
    <!--header-->

     



<div class = "grid-row">
<!--table conatining pet image pet info and the camera to link to the simulation-->
<table style="
    width: 60%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 20px;
">
<!--division of the image-->
<tr>
<td>
      <div class ="arr"> 
<%= image_tag @register.image.url(:large) %>
</div>
</td>

<td >


          <!--here the camera image so user can open the cam to see the pet-->

            <article class="card card--link grid-col-4 color-scheme--white grid-row grid-col--no-padding"style="
    border-radius: 20px;
">
  <div class="aal
  ">
    <img src="http://media.idownloadblog.com/wp-content/uploads/2013/05/Analog-Camera-for-iOS-app-icon-full-size.jpg" width="100" height="100"/> 
</div>
  <div class="grid-col-12 grid-col--align-center">
    <hr>
    <h3>check on them any time</h3>
  </div>
  <div class="grid-col-12 grid-col--align-center grid-col--no-margin">
    <div class="last-progress margin-top-bottom--1">
      <small>camera allow you to see them </small>

    </div>
  </div>
  

  <a href="#"></a>

</article>
</td>
</tr>
</table>





<!--div containing the pet info-->
<table style = "
width:90%;
margin:auto; 
">
<tr>
<td>

<div class = "pet_text">
<p>
  
  <%= @register.name %>
</p>
<p>
  <strong>Breed:</strong>
  <%= @register.breed %>
</p>

<p>
  <strong>Species:</strong>
  <%= @register.species %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @register.gender %>
</p>

<p>
<strong>Date Of Birth:</strong>
  <%= @register.date_of_birth %>
</p>

      <% pet_id = @register.id %>
      <% Rails.cache.write(:pet_id, pet_id) %>
      
      
</div>
</td>
<!--div containing the list of ur buddies with otion to delete or edit them-->
<div class="pet_b">

    <% @buddies.each do |buddy| %>
    
 <h1>My Buddies</h1>
        <h1><%= buddy.username %>
        <%= buddy.register.name %>
        <%= buddy.can_feed %>
        <%= buddy.can_schedule %>
        <%= link_to 'Edit', edit_buddy_path(buddy) %>
        <%= link_to 'Delete', buddy, method: :delete, data: { confirm: 'Are you sure?' } %></h1>
      <!--here u can add buddy-->

      <div class="button">
      <a href="/buddies/new">Add Buddy</a>
      </div>
</div>
<% end %>
</td>

</tr>
 </table>


<!--div for deleting and editing pet-->

 <div class = 'edit'>   
<h2>

<%= link_to 'Edit', edit_register_path(@register) %>
      <%= link_to 'Delete', register_path(@register),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</h2>
</div>

      <div class="button">
      <h3>
      <a href="/buddies/new">Add Buddy</a>
      </h3>
      </div>