config/routes.rb
Rails.application.routes.draw do
  resources :foods

  resources :devices
  resources :events

  resources :buddies

  resources :reminders

  resources :registers
  
  resources :feeds

  devise_for :users
  devise_for :registers
  devise_scope :user do
  authenticated :user do
    root :to => 'feeds#index'
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root

      end
end
 
 get "devices/registers2"
 get "devices/index"
 match "devices/register2" => "devices#register2", :via => :post

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :User
  validates :body , :due_date , presence: true
  validates_datetime :due_date , :on_or_after => :today
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)
    @reminder.User= current_user

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:body, :due_date)
    end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form' %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Due date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.body %></td>
        <td><%= reminder.due_date %></td>
        <td><%= reminder.User %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<div class="menu">
      
      <!-- Menu icon -->
      <div class="icon-close">
        <img src='close.png'>
      </div>

<!-- Menu -->
      <ul >
     

<li><%= link_to 'Back', feeds_path %></li>
      </ul>
    </div>
     <!-- Main body -->
    <div class="jumbotron">

      <div class="icon-menu">
        <i class="fa fa-bars"></i>
        Menu
      </div>
   
<h1>New Reminder</h1>

<%= render 'form' %>

</div>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @reminder.body %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @reminder.due_date %>
</p>


<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', feeds_path %>