config/routes.rb
Rails.application.routes.draw do
  resources :foods

  resources :devices
  resources :events

  resources :buddies

  resources :reminders

  resources :registers
  
  resources :feeds

  devise_for :users
  devise_for :registers
  devise_scope :user do
  authenticated :user do
    root :to => 'feeds#index'
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root

      end
end
 
 get "devices/registers2"
 get "devices/index"
 match "devices/register2" => "devices#register2", :via => :post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="../app/assets/stylesheets/font-awesome.min.css" rel="stylesheet">
    <link href='../app/assets/stylesheets/style.css' rel='stylesheet'>
     <link href='../app/assets/stylesheets/core.css' rel='stylesheet'>
      <link href='../app/assets/stylesheets/show.css' rel='stylesheet'>

  <title>CloudPets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
</head>
<body>
<!--user menu--><% if current_user.present? %>
      <div class="menu">
      <div class="mm">
    
     

      <div class="sign up">
       <ul >
       <!--links go here-->
        <li><%= link_to 'My Pets' , registers_path %></li>
        <li><%=link_to 'My devices', devices_path %></li>
        <li><%=link_to 'New Reminder', new_reminder_path %></li>
        <li><%=link_to 'My schedule', events_path %></li>
         <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </ul>
      </div> </div>
    </div><% end %>
 <!--ading landing page and doing the same with the navigation bar-->

 <header id="header">
  
  <article class="fit-fixed" id="header__nav-container">
    <div id="header__nav" class="grid-col-12 grid-row grid-col--no-spacing">
      


<div class = "navbarmenu">
        <div class="header__dynamic-width-col">
            <a id="header__menu-me" class="js-toggle-profile-dropdown header__nav__link">
              <div id="user-dropdown" class="header__nav__link__label">
                
                <h5>
                 MENU ☰
                  </h5>
              </div>
            </a>
        </div>

 <div class="header__dynamic-width-col">
            
              <div id="user-dropdown" class="header__nav__link__label">
                
                <%= link_to 'My Pets' , registers_path %>
              </div>
            
        </div>
</div>

            <div id="header__notifications" class="header__dynamic-width-col" exclude="phone">
                          </div>




      </div>


    <div id="header__logo">
    <table><tr><td id="header__logo__link">
    
        
        <%= link_to image_tag("https://lh3.googleusercontent.com/TfvFMFe9j9ezkuuVZf8_hQ7ZNcX-xzFdWF4fnyLfgNjkGyTsGYjFRj4maBdPvo41PDBQrg=s85"), feeds_path %>

 </td><td>   <p>CLOUDPET</p>
</td></tr></table>
</div>




  </article>
  
</header>
    <main class="ppss 
">
      
<%= yield %>

</main>

 

 <script src="../app/assets/javascripts/jquery.min.js"></script>
    <script src="../app/assets/javascripts/app.js"></script>



<footer style="
    height: initial;
    background-color: #BDC3C7;
    position: fixed;
    bottom: 0px;
    width: 100%;
">
        <p>© 2015 BTQ, Inc. · <a href="file:///C:/Users/youssef%20%20adel/Desktop/landmerge_files/landmerge.html">Privacy</a> · <a href="file:///C:/Users/youssef%20%20adel/Desktop/landmerge_files/landmerge.html">Terms</a></p>
      </footer>
</body>
</html>